"""Canonical Data Contracts & Receipts for Host-Native Specialist Dispatch (Milestone R11).

Strictly stdlib-only. Implements immutable domain value objects and receipt minting.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import hashlib
from typing import Any, Dict, Optional
import uuid

from scripts.domain.common import BaseDomainModel, ValidationError, canonical_json
from scripts.domain.delegation import DelegationEnvelope, HostCapabilities
from scripts.domain.receipts import DispatchReceipt, ReceiptType


class DispatchStatus(str, Enum):
    """Lifecycle state of an individual specialist dispatch attempt."""
    PENDING = "PENDING"                    # Dispatch initiated, awaiting adapter execution
    DISPATCHED = "DISPATCHED"              # Successfully launched on target host substrate
    ACKNOWLEDGED = "ACKNOWLEDGED"          # Host runtime confirmed specialist accepted task
    FAILED_RETRYABLE = "FAILED_RETRYABLE"  # Transient failure (e.g. rate limit, spawn timeout)
    FAILED_TERMINAL = "FAILED_TERMINAL"    # Non-retryable failure (e.g. invalid role, missing binary)
    UNSUPPORTED = "UNSUPPORTED"            # Host lacks required capabilities for envelope
    CANCELLED = "CANCELLED"                # Dispatch aborted prior to specialist execution


@dataclass(frozen=True)
class HostExecutionBinding(BaseDomainModel):
    """Captures the concrete execution context binding between Squad and the Host."""
    host_kind: str                        # "antigravity", "codex", "gemini_cli", "claude", "fake"
    host_version: str                     # Host environment version or build identifier
    session_id: str                       # Bound MCP session UUID
    execution_handle: str                 # Host-native handle (e.g. conversation_id, pid, task_id)
    dispatch_mode: str                    # "native_subagent", "headless_cli", "background_process"
    capabilities: HostCapabilities        # Snapshot of active host capabilities at dispatch time
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.host_kind or not self.host_kind.strip():
            raise ValidationError("host_kind must not be empty")
        if not self.session_id or not self.session_id.strip():
            raise ValidationError("session_id must not be empty")
        if not self.dispatch_mode or not self.dispatch_mode.strip():
            raise ValidationError("dispatch_mode must not be empty")


@dataclass(frozen=True)
class HostDispatchResult(BaseDomainModel):
    """Normalized response returned by a HostDispatchPort implementation upon dispatch."""
    status: DispatchStatus
    host_execution_id: str                # Unique identifier generated by host (or synthetic handle)
    evidence_payload: Dict[str, Any]      # Host-native launch receipt or process attributes
    error_code: Optional[str] = None      # Standardized failure code if status in FAILED_*
    error_message: Optional[str] = None   # Human-readable diagnostics
    dispatched_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self) -> None:
        if not self.host_execution_id or not self.host_execution_id.strip():
            raise ValidationError("host_execution_id must not be empty")


@dataclass(frozen=True)
class HostStatusResult(BaseDomainModel):
    """Status probe result for an active or completed host execution."""
    host_execution_id: str
    status: DispatchStatus
    is_alive: bool
    details: Dict[str, Any] = field(default_factory=dict)


def compute_evidence_hash(evidence_payload: Dict[str, Any]) -> str:
    """Computes deterministic SHA-256 hash of evidence payload."""
    serialized = canonical_json(evidence_payload or {})
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def mint_dispatch_receipt(
    envelope: DelegationEnvelope,
    dispatch_result: HostDispatchResult,
    receipt_id: Optional[str] = None,
    dispatched_at: Optional[datetime] = None,
) -> DispatchReceipt:
    """Mints an immutable canonical DispatchReceipt bound to the envelope and host evidence.
    
    Invariants:
    - instruction_hash matches envelope.instruction_hash verbatim
    - evidence_hash is sha256(canonical_json(evidence_payload))
    - target_agent_id matches envelope.target_role
    - work_item_id matches envelope.work_item_id
    """
    assigned_receipt_id = receipt_id or f"RCP-DISP-{uuid.uuid4().hex[:12]}"
    evidence_hash = compute_evidence_hash(dispatch_result.evidence_payload)
    effective_dispatched_at = dispatched_at or dispatch_result.dispatched_at

    return DispatchReceipt(
        receipt_id=assigned_receipt_id,
        receipt_type=ReceiptType.DISPATCH.value,
        work_item_id=envelope.work_item_id,
        agent_id=envelope.sender_role,
        instruction_hash=envelope.instruction_hash,
        evidence_hash=evidence_hash,
        target_agent_id=envelope.target_role,
        delegation_id=envelope.delegation_id,
        dispatched_at=effective_dispatched_at,
    )
