"""Domain models for External Synchronization, ADO Bindings and Reconciliation Decisions.

Strictly stdlib-only.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

from .common import BaseDomainModel, ValidationError


class SyncStatus(str, Enum):
    SYNCED = "SYNCED"
    PENDING_CREATE = "PENDING_CREATE"
    PENDING_UPDATE = "PENDING_UPDATE"
    PENDING_DELETE = "PENDING_DELETE"
    CONFLICT = "CONFLICT"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class ReconciliationAction(str, Enum):
    NOOP = "NOOP"
    APPLY_LOCAL_TO_REMOTE = "APPLY_LOCAL_TO_REMOTE"
    APPLY_REMOTE_TO_LOCAL = "APPLY_REMOTE_TO_LOCAL"
    BLOCK_ILLEGAL_REMOTE_TRANSITION = "BLOCK_ILLEGAL_REMOTE_TRANSITION"
    CONFLICT_REQUIRES_RESOLUTION = "CONFLICT_REQUIRES_RESOLUTION"


@dataclass(frozen=True)
class AdoWorkItemBinding(BaseDomainModel):
    """Specific entity binding between a canonical WorkItem and an Azure DevOps work item."""

    work_item_id: str
    ado_id: int
    remote_url: str
    remote_rev: int
    last_synced_at: datetime = field(default_factory=datetime.utcnow)
    sync_hash: str = ""

    def __post_init__(self) -> None:
        if not self.work_item_id or not self.work_item_id.strip():
            raise ValidationError("work_item_id must not be empty")
        if self.ado_id <= 0:
            raise ValidationError(f"ado_id must be a positive integer: {self.ado_id}")
        if not self.remote_url or not self.remote_url.strip():
            raise ValidationError("remote_url must not be empty")


@dataclass(frozen=True)
class SyncState(BaseDomainModel):
    """Synchronous status tracking entity for external delivery backend reconciliation."""

    work_item_id: str
    status: SyncStatus
    backend_kind: str
    remote_id: Optional[str] = None
    retry_count: int = 0
    last_error: Optional[str] = None
    last_synced_at: Optional[datetime] = None
    updated_at: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self) -> None:
        if not self.work_item_id or not self.work_item_id.strip():
            raise ValidationError("work_item_id must not be empty")
        if not self.backend_kind or not self.backend_kind.strip():
            raise ValidationError("backend_kind must not be empty")
        if self.retry_count < 0:
            raise ValidationError("retry_count cannot be negative")


@dataclass(frozen=True)
class ReconciliationDecision(BaseDomainModel):
    """Deterministic drift resolution decision generated by reconciliation evaluation."""

    work_item_id: str
    action: ReconciliationAction
    reason: str
    local_state: str
    remote_state: str
    detected_at: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self) -> None:
        if not self.work_item_id or not self.work_item_id.strip():
            raise ValidationError("work_item_id must not be empty")
        if not self.reason or not self.reason.strip():
            raise ValidationError("reason must not be empty")


@dataclass(frozen=True)
class ReconciliationOutcome(BaseDomainModel):
    """Execution result of applying a reconciliation decision."""

    decision_id: str
    work_item_id: str
    action_taken: ReconciliationAction
    success: bool
    details: str
    resolved_at: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self) -> None:
        if not self.decision_id or not self.decision_id.strip():
            raise ValidationError("decision_id must not be empty")
        if not self.work_item_id or not self.work_item_id.strip():
            raise ValidationError("work_item_id must not be empty")
