"""Build a deterministic, fail-closed Agents Squad 2.0 file manifest.

O que é: scanner read-only e serializador de proveniência file-by-file.
Responsabilidade: classificar cada arquivo capturado exatamente uma vez e
falhar diante de path, hash, symlink, executável ou reconciliação inválidos.
Pra que serve: fundamentar uma distribuição limpa sem copiar work histórico.
Comportamento em falha: não grava outputs até toda a árvore ser validada.
Conexões: contracts/distribution-file.schema.json e distribution/*.json*.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any


SOURCE_REVISION = "UNVERIFIED"
CURRENT_EPIC = "work/agent_squad/EPIC-SQUAD-EVOLUTION-20260818/"
VOLATILE_EVIDENCE_PREFIXES = (
    "work/agent_squad/EPIC-SQUAD-EVOLUTION-20260818/documentation/",
    "work/agent_squad/EPIC-SQUAD-EVOLUTION-20260818/gate-decisions/",
    "work/agent_squad/EPIC-SQUAD-EVOLUTION-20260818/traceability/",
    "work/agent_squad/EPIC-SQUAD-EVOLUTION-20260818/memory/",
)
SELF_OUTPUTS = {
    "distribution/source-snapshot.json",
    "distribution/files.manifest.jsonl",
    "archive/archive-manifest.jsonl",
}
MATERIALIZED_OUTPUT_PARTS = {"materialized"}
EXCLUDED_PARTS = {".locks", ".mimosa", ".pytest_cache", ".venv", ".vercel", ".zcode", "__pycache__", ".temp"}
ROOT_EXCLUDED_FILES = {".coverage", ".env.local"}
ROOT_DISTRIBUTION_FILES = {
    ".dockerignore",
    ".gitattributes",
    ".gitignore",
    "AGENTS.md",
    "Dockerfile",
    "CLAUDE.md",
    "CODEX.md",
    "GEMINI.md",
    "INTEGRATION_TEST_REPORT.md",
    "README.md",
    "THIRD_PARTY_NOTICES.md",
    "PROVENANCE.yaml",
    "docker-compose.yml",
    "install.ps1",
    "pyproject.toml",
    "requirements.txt",
}
ROOT_ARCHIVE_FILES = {"findings.md", "progress.md", "task_plan.md", "FORGE.md"}
DISTRIBUTION_TOP = {
    ".github",
    "agents",
    "banco",
    "config",
    "contracts",
    "docs",
    "integrations",
    "rendered_prompts",
    "scripts",
    "skills",
    "tasks",
    "templates",
    "workflows",
    "distribution",
    "dist",
    "archive",
    "backups",
    "domain",
    "application",
    "ports",
    "adapters",
    "bootstrap",
    "legacy-runtime",
}
NEW_PATHS = {
    "contracts/distribution-file.schema.json",
    "scripts/build_file_manifest.py",
    "scripts/tests/test_build_file_manifest.py",
}
EXECUTABLE_EXTENSIONS = {".bat", ".cmd", ".com", ".exe", ".ps1", ".sh"}
HASH_RE = re.compile(r"^[a-f0-9]{64}$")


class ManifestError(RuntimeError):
    pass


@dataclass(frozen=True)
class BuildResult:
    """Resultado imutável da compilação e validação do manifesto de arquivos."""
    records: tuple[dict[str, Any], ...]
    counts: dict[str, int]
    snapshot_digest: str


def validate_relative_path(value: str) -> str:
    """Valida se uma string representa um caminho relativo POSIX canônico seguro."""
    if not value or "\\" in value or value.startswith("/") or re.match(r"^[A-Za-z]:", value):
        raise ManifestError(f"path must be relative POSIX: {value!r}")
    pure = PurePosixPath(value)
    if pure.is_absolute() or ".." in pure.parts or any(part in {"", "."} for part in pure.parts):
        raise ManifestError(f"path must be relative POSIX: {value!r}")
    return pure.as_posix()


def _policy(
    classification: str,
    treatment: str,
    lifecycle: str,
    destination: str,
    reason: str,
    *,
    origin: str = "agents-squad-baseline",
    owner: str = "delivery-orchestrator",
    license_name: str = "UNVERIFIED",
    sensitivity: str = "internal",
    executable: bool = False,
) -> dict[str, Any]:
    return {
        "origin": origin,
        "source_revision": SOURCE_REVISION,
        "classification": classification,
        "treatment": treatment,
        "lifecycle": lifecycle,
        "executable": executable,
        "license": license_name,
        "sensitivity": sensitivity,
        "owner": owner,
        "reason": reason,
        "destination": destination,
    }


def classify(relative: str) -> dict[str, Any]:
    """Classifica um arquivo de acordo com as políticas de ciclo de vida e distribuição."""
    relative = validate_relative_path(relative)
    parts = PurePosixPath(relative).parts
    suffix = PurePosixPath(relative).suffix.lower()
    actual_executable = suffix in EXECUTABLE_EXTENSIONS

    if relative in ROOT_EXCLUDED_FILES:
        return _policy("tooling", "generated", "transient", "excluded", "local generated coverage data", origin="generated-local")
    if any(part in EXCLUDED_PARTS for part in parts) or suffix in {".pyc", ".pyo"}:
        return _policy("tooling", "generated", "transient", "excluded", "cache or generated bytecode", origin="generated-local", executable=actual_executable)
    if any(relative.startswith(prefix) for prefix in VOLATILE_EVIDENCE_PREFIXES):
        return _policy("archive", "generated", "active-evidence", "excluded", "mutable control-plane evidence is packaged separately after freeze")
    if relative.startswith("work/"):
        if relative.startswith(CURRENT_EPIC):
            return _policy("archive", "adapted", "release-evidence", "archive", "current 2.0 epic evidence is not runtime distribution", executable=actual_executable)
        return _policy("archive", "reused", "historical", "archive", "historical work is retained outside the clean distribution", executable=actual_executable)
    if relative in ROOT_ARCHIVE_FILES or relative.startswith("audits/"):
        return _policy("archive", "reused", "historical", "archive", "historical project evidence")
    if relative in ROOT_DISTRIBUTION_FILES:
        treatment = "new" if relative == "PROVENANCE.yaml" else "reused"
        origin = "agents-squad-2.0" if treatment == "new" else "agents-squad-baseline"
        return _policy("doc", treatment, "runtime", "distribution", "root operational contract or documentation", origin=origin, executable=actual_executable)
    top = parts[0]
    if top not in DISTRIBUTION_TOP:
        raise ManifestError(f"unclassified file: {relative}")

    if top == "agents":
        classification, owner = "module", "delivery-orchestrator"
    elif top in {"config", "contracts", "domain", "application", "ports"}:
        classification, owner = "core", "solution-architect"
    elif top in {"scripts", ".github", "distribution", "dist", "archive", "backups", "bootstrap", "banco", "integrations"}:
        classification, owner = "tooling", "platform-engineer"
    elif top in {"adapters", "legacy-runtime"}:
        classification, owner = "adapter", "solution-architect"
    elif top == "skills":
        classification, owner = "module", "skill-curator"
    elif top in {"templates", "tasks", "workflows"}:
        classification, owner = "adapter", "delivery-orchestrator"
    elif top in {"docs", "rendered_prompts"}:
        classification, owner = "doc", "technical-writer"
    else:
        raise ManifestError(f"unclassified file: {relative}")

    treatment = "new" if relative in NEW_PATHS else "reused"
    origin = "agents-squad-2.0" if treatment == "new" else "agents-squad-baseline"
    if relative in {"scripts/agent_squad.py", "scripts/tests/test_agent_squad.py"}:
        treatment, origin = "adapted", "agents-squad-baseline"
    if "/tests/" in f"/{relative}" or relative.startswith("scripts/tests/"):
        classification = "test"
    return _policy(classification, treatment, "runtime", "distribution", "allowlisted runtime candidate", origin=origin, owner=owner, executable=actual_executable)


def _is_mode_executable(path: Path) -> bool:
    return bool(path.stat(follow_symlinks=False).st_mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))


def record_for(root: Path, path: Path, relative: str, policy: dict[str, Any]) -> dict[str, Any]:
    """Cria um registro imutável do manifesto com cálculo de hash SHA-256 e tamanho."""
    relative = validate_relative_path(relative)
    if path.is_symlink():
        raise ManifestError(f"symlink is not allowed: {relative}")
    resolved_root = root.resolve(strict=True)
    resolved_path = path.resolve(strict=True)
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError as exc:
        raise ManifestError(f"path escapes root: {relative}") from exc
    mode_executable = _is_mode_executable(path)
    suffix_executable = path.suffix.lower() in EXECUTABLE_EXTENSIONS
    if (mode_executable or suffix_executable) and not policy["executable"]:
        raise ManifestError(f"undeclared executable: {relative}")
    payload = path.read_bytes()
    record = {
        "path": relative,
        "sha256": hashlib.sha256(payload).hexdigest(),
        "size": len(payload),
        **policy,
    }
    validate_record(record)
    return record


def validate_record(record: dict[str, Any]) -> None:
    """Valida se todos os campos obrigatórios e formatos do registro do manifesto estão corretos."""
    required = {"path", "sha256", "size", "origin", "source_revision", "classification", "treatment", "lifecycle", "executable", "license", "sensitivity", "owner", "reason", "destination"}
    if set(record) != required:
        raise ManifestError(f"FileRecord fields mismatch: {sorted(set(record) ^ required)}")
    validate_relative_path(record["path"])
    if not HASH_RE.fullmatch(record["sha256"]):
        raise ManifestError(f"invalid sha256: {record['path']}")
    if not isinstance(record["size"], int) or record["size"] < 0:
        raise ManifestError(f"invalid size: {record['path']}")
    if record["classification"] not in {"core", "adapter", "module", "doc", "test", "tooling", "archive"}:
        raise ManifestError(f"invalid classification: {record['path']}")
    if record["treatment"] not in {"new", "adapted", "reused", "generated"}:
        raise ManifestError(f"invalid treatment: {record['path']}")
    if record["destination"] not in {"distribution", "archive", "excluded"}:
        raise ManifestError(f"invalid destination: {record['path']}")
    for key in ("origin", "source_revision", "license", "owner", "reason"):
        if not isinstance(record[key], str) or not record[key]:
            raise ManifestError(f"missing {key}: {record['path']}")


def verify_record(root: Path, record: dict[str, Any]) -> None:
    """Verifica a integridade física de um arquivo no disco contra o registro correspondente."""
    validate_record(record)
    target = root / Path(*PurePosixPath(record["path"]).parts)
    if target.is_symlink():
        raise ManifestError(f"symlink is not allowed: {record['path']}")
    if not target.is_file():
        raise ManifestError(f"file missing: {record['path']}")
    payload = target.read_bytes()
    if hashlib.sha256(payload).hexdigest() != record["sha256"] or len(payload) != record["size"]:
        raise ManifestError(f"hash mismatch: {record['path']}")


def load_retained_archive(root: Path) -> dict[str, dict[str, Any]]:
    """Carrega o manifesto de registros retidos do arquivo permanente."""
    manifest = root / "archive/archive-manifest.jsonl"
    if not manifest.is_file():
        return {}
    retained: dict[str, dict[str, Any]] = {}
    for number, line in enumerate(manifest.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ManifestError(f"invalid archive manifest line {number}: {exc}") from exc
        validate_record(record)
        if record["destination"] != "archive":
            raise ManifestError(f"non-archive retained record: {record['path']}")
        relative = record["path"]
        if relative in retained:
            raise ManifestError(f"duplicate archive record: {relative}")
        materialized = root / "archive/materialized" / Path(*PurePosixPath(relative).parts)
        if not materialized.is_file() or materialized.is_symlink():
            raise ManifestError(f"retained archive missing: {relative}")
        payload = materialized.read_bytes()
        if len(payload) != record["size"] or hashlib.sha256(payload).hexdigest() != record["sha256"]:
            raise ManifestError(f"retained archive hash mismatch: {relative}")
        retained[relative] = record
    return retained


def build(root: Path) -> BuildResult:
    """Constrói o snapshot completo de manifesto de arquivos para o diretório raiz."""
    root = root.resolve(strict=True)
    if not root.is_dir():
        raise ManifestError(f"root is not a directory: {root}")
    retained_archive = load_retained_archive(root)
    records: list[dict[str, Any]] = []
    seen: set[str] = set()
    for directory, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        current = Path(directory)
        for name in sorted(dirnames):
            child = current / name
            if child.is_symlink():
                relative = child.relative_to(root).as_posix()
                raise ManifestError(f"symlink is not allowed: {relative}")
        current_relative = current.relative_to(root).as_posix()
        dirnames[:] = [
            name
            for name in dirnames
            if not (
                current_relative in {"distribution", "archive"}
                and (name in MATERIALIZED_OUTPUT_PARTS or name.startswith(".materialized."))
            )
        ]
        dirnames.sort()
        for name in sorted(filenames):
            path = current / name
            relative = path.relative_to(root).as_posix()
            if relative in SELF_OUTPUTS:
                continue
            if relative in seen:
                raise ManifestError(f"duplicate path: {relative}")
            seen.add(relative)
            records.append(record_for(root, path, relative, classify(relative)))
    live_by_path = {record["path"]: record for record in records}
    for relative, archived_record in retained_archive.items():
        live_record = live_by_path.get(relative)
        if live_record is None:
            records.append(archived_record)
    records.sort(key=lambda item: item["path"].encode("utf-8"))
    if len(records) != len(seen | set(retained_archive)):
        raise ManifestError("incomplete reconciliation")
    counts = {name: 0 for name in ("distribution", "archive", "excluded")}
    for record in records:
        counts[record["destination"]] += 1
        target = root / Path(*PurePosixPath(record["path"]).parts)
        if target.is_file():
            verify_record(root, record)
        elif record["path"] not in retained_archive:
            raise ManifestError(f"file missing: {record['path']}")
    if sum(counts.values()) != len(records):
        raise ManifestError("incomplete reconciliation")
    canonical = b"".join((json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8") for record in records)
    return BuildResult(tuple(records), counts, hashlib.sha256(canonical).hexdigest())


def serialize(result: BuildResult) -> tuple[bytes, bytes]:
    """Serializa o snapshot e o manifesto JSONL de arquivos."""
    manifest = b"".join((json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8") for record in result.records)
    snapshot = {
        "schema_version": 1,
        "git_revision": "UNVERIFIED",
        "snapshot_digest": result.snapshot_digest,
        "algorithm": "sha256(canonical-jsonl-records)",
        "records": len(result.records),
        "counts": result.counts,
        "reconciliation": {"captured": len(result.records), "classified": sum(result.counts.values()), "complete": len(result.records) == sum(result.counts.values())},
        "self_outputs_excluded": sorted(SELF_OUTPUTS),
    }
    return (json.dumps(snapshot, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8"), manifest


def _output_under_root(root: Path, output: Path) -> Path:
    resolved_root = root.resolve(strict=True)
    candidate = output.resolve(strict=False)
    try:
        candidate.relative_to(resolved_root)
    except ValueError as exc:
        raise ManifestError(f"output escapes root: {output}") from exc
    return candidate


def main(argv: list[str] | None = None) -> int:
    """Ponto de entrada CLI para geração e verificação do manifesto de arquivos."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--snapshot", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    args = parser.parse_args(argv)
    root = args.root.resolve(strict=True)
    snapshot_path = _output_under_root(root, args.snapshot)
    manifest_path = _output_under_root(root, args.manifest)
    if snapshot_path.relative_to(root).as_posix() != "distribution/source-snapshot.json" or manifest_path.relative_to(root).as_posix() != "distribution/files.manifest.jsonl":
        raise ManifestError("outputs must use the governed distribution paths")
    result = build(root)
    snapshot, manifest = serialize(result)
    snapshot_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot_path.write_bytes(snapshot)
    manifest_path.write_bytes(manifest)
    print(json.dumps({"result": "MANIFEST_OK", "records": len(result.records), "counts": result.counts, "snapshot_digest": result.snapshot_digest}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
